// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: predict.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date   string  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	CoImf1 float64 `protobuf:"fixed64,2,opt,name=co_imf1,json=coImf1,proto3" json:"co_imf1,omitempty"`
	CoImf2 float64 `protobuf:"fixed64,3,opt,name=co_imf2,json=coImf2,proto3" json:"co_imf2,omitempty"`
	CoImf3 float64 `protobuf:"fixed64,4,opt,name=co_imf3,json=coImf3,proto3" json:"co_imf3,omitempty"`
	CoImf4 float64 `protobuf:"fixed64,5,opt,name=co_imf4,json=coImf4,proto3" json:"co_imf4,omitempty"`
	Target float64 `protobuf:"fixed64,6,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predict_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{0}
}

func (x *DataPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DataPoint) GetCoImf1() float64 {
	if x != nil {
		return x.CoImf1
	}
	return 0
}

func (x *DataPoint) GetCoImf2() float64 {
	if x != nil {
		return x.CoImf2
	}
	return 0
}

func (x *DataPoint) GetCoImf3() float64 {
	if x != nil {
		return x.CoImf3
	}
	return 0
}

func (x *DataPoint) GetCoImf4() float64 {
	if x != nil {
		return x.CoImf4
	}
	return 0
}

func (x *DataPoint) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

type PredictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DataPoint `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predict_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{1}
}

func (x *PredictRequest) GetData() []*DataPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

type PredictResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val float64 `protobuf:"fixed64,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predict_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{2}
}

func (x *PredictResponse) GetVal() float64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type PredictAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DataPoint `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *PredictAllRequest) Reset() {
	*x = PredictAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predict_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictAllRequest) ProtoMessage() {}

func (x *PredictAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictAllRequest.ProtoReflect.Descriptor instead.
func (*PredictAllRequest) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{3}
}

func (x *PredictAllRequest) GetData() []*DataPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

type PredictAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val []float64 `protobuf:"fixed64,1,rep,packed,name=val,proto3" json:"val,omitempty"`
}

func (x *PredictAllResponse) Reset() {
	*x = PredictAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_predict_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PredictAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictAllResponse) ProtoMessage() {}

func (x *PredictAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictAllResponse.ProtoReflect.Descriptor instead.
func (*PredictAllResponse) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{4}
}

func (x *PredictAllResponse) GetVal() []float64 {
	if x != nil {
		return x.Val
	}
	return nil
}

var File_predict_proto protoreflect.FileDescriptor

var file_predict_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74,
	0x61, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f,
	0x5f, 0x69, 0x6d, 0x66, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x63, 0x6f, 0x49,
	0x6d, 0x66, 0x31, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x5f, 0x69, 0x6d, 0x66, 0x32, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x63, 0x6f, 0x49, 0x6d, 0x66, 0x32, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x6f, 0x5f, 0x69, 0x6d, 0x66, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x63,
	0x6f, 0x49, 0x6d, 0x66, 0x33, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x5f, 0x69, 0x6d, 0x66, 0x34,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x63, 0x6f, 0x49, 0x6d, 0x66, 0x34, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x38, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x23, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x3b, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x26, 0x0a, 0x12, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x32, 0x90, 0x01, 0x0a, 0x09, 0x50,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x3c, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x50, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x41, 0x6c, 0x6c, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x50,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a,
	0x05, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_predict_proto_rawDescOnce sync.Once
	file_predict_proto_rawDescData = file_predict_proto_rawDesc
)

func file_predict_proto_rawDescGZIP() []byte {
	file_predict_proto_rawDescOnce.Do(func() {
		file_predict_proto_rawDescData = protoimpl.X.CompressGZIP(file_predict_proto_rawDescData)
	})
	return file_predict_proto_rawDescData
}

var file_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_predict_proto_goTypes = []any{
	(*DataPoint)(nil),          // 0: predict.DataPoint
	(*PredictRequest)(nil),     // 1: predict.PredictRequest
	(*PredictResponse)(nil),    // 2: predict.PredictResponse
	(*PredictAllRequest)(nil),  // 3: predict.PredictAllRequest
	(*PredictAllResponse)(nil), // 4: predict.PredictAllResponse
}
var file_predict_proto_depIdxs = []int32{
	0, // 0: predict.PredictRequest.data:type_name -> predict.DataPoint
	0, // 1: predict.PredictAllRequest.data:type_name -> predict.DataPoint
	1, // 2: predict.Predictor.Predict:input_type -> predict.PredictRequest
	3, // 3: predict.Predictor.PredictAll:input_type -> predict.PredictAllRequest
	2, // 4: predict.Predictor.Predict:output_type -> predict.PredictResponse
	4, // 5: predict.Predictor.PredictAll:output_type -> predict.PredictAllResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_predict_proto_init() }
func file_predict_proto_init() {
	if File_predict_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_predict_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DataPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predict_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PredictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predict_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PredictResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predict_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PredictAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_predict_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PredictAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_predict_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_predict_proto_goTypes,
		DependencyIndexes: file_predict_proto_depIdxs,
		MessageInfos:      file_predict_proto_msgTypes,
	}.Build()
	File_predict_proto = out.File
	file_predict_proto_rawDesc = nil
	file_predict_proto_goTypes = nil
	file_predict_proto_depIdxs = nil
}
