name: go_ci

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check Secrets
        run: |
          echo "SSH_HOST is set"
          echo "SSH_USER is set"
          echo "SSH_PASS is set (hidden)"
          echo "SSH_KEY is set (hidden)"
        env:
          SSH_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_USER: ${{ secrets.REMOTE_USER }}
          SSH_PASS: ${{ secrets.SHH_PASSWORD }}
          SSH_KEY: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SHH_PASSWORD}}
          port: 22  # 服务器 SSH 端口
          script: |
            cd /root/project/financia_data_go  # 切换到你的项目目录
            git pull
            go mod vendor
            ./nohupRun.sh

