name: go_ci

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SHH_PASSWORD}}
          port: 22  # 服务器 SSH 端口
          script: |
            cd /root/project/financia_data_go  # 切换到你的项目目录
            git pull
            go mod vendor
            ./nohupRun.sh

